# Generated by Django 3.2.5 on 2021-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='blogimages/')),
                ('product_title', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=20)),
                ('product_desc', models.TextField()),
                ('product_count', models.TextField(max_length=10)),
                ('product_slug', models.SlugField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
