# Generated by Django 3.2.5 on 2021-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_count',
            field=models.CharField(max_length=10),
        ),
    ]
