# Generated by Django 3.2.5 on 2021-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_products_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
