# Generated by Django 3.2.5 on 2021-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_products_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
