# Generated by Django 3.2.5 on 2021-08-02 10:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='blogimages/'),
        ),
    ]
