# Generated by Django 3.2.5 on 2021-08-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('upi_transaction_id', models.CharField(max_length=100)),
                ('upi_id', models.CharField(max_length=200)),
                ('payment_proof', models.FileField(upload_to='paymentproof/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('product_quantity', models.IntegerField()),
                ('single_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField()),
                ('customer_contry', models.CharField(choices=[('1', 'India'), ('2', 'USA'), ('3', 'Canada'), ('4', 'Bhutan'), ('5', 'Japan')], max_length=30)),
                ('customer_state', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('city_zip', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile_number', models.BigIntegerField()),
                ('order_status', models.CharField(choices=[('1', 'Placed'), ('2', 'Confirm'), ('3', 'Out for Delivery'), ('4', 'Complete'), ('5', 'Failed')], max_length=100)),
                ('order_payment_type', models.CharField(choices=[('1', 'Placed'), ('2', 'Confirm'), ('3', 'Out for Delivery'), ('4', 'Complete'), ('5', 'Failed')], max_length=100)),
                ('order_payment_status', models.CharField(choices=[('1', 'Paid'), ('2', 'Pending'), ('3', 'Failed')], max_length=100)),
                ('total_order_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_payment_ref', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customepaymentmethod')),
                ('products', models.ManyToManyField(to='app.OrderProductInfo')),
            ],
        ),
    ]
