# Generated by Django 3.2.5 on 2021-08-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customepaymentmethod_orderproductinfo_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_payment_type',
            field=models.CharField(choices=[('1', 'Paytm'), ('2', 'Razorpay'), ('3', 'Custome')], max_length=100),
        ),
        migrations.CreateModel(
            name='CartProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('single_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_verify_code', models.CharField(max_length=255)),
                ('cart_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('products_cart', models.ManyToManyField(to='app.CartProductInfo')),
            ],
        ),
    ]
