# Generated by Django 3.2.5 on 2021-08-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210805_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_verify_code',
        ),
    ]
